name: torch
channels:
  - defaults
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - abseil-cpp=20230802.0=h313beb8_1
  - absl-py=1.4.0=py311hca03da5_0
  - aiofiles=22.1.0=py311hca03da5_0
  - aiohttp=3.8.5=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py311hca03da5_0
  - anyio=3.5.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - arrow-cpp=14.0.2=hc7aafb3_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - aws-c-auth=0.6.21=h284e69b_0
  - aws-c-cal=0.5.20=h7a1267a_3
  - aws-c-common=0.8.5=h1a8c8d9_0
  - aws-c-compression=0.2.16=ha56e2a8_0
  - aws-c-event-stream=0.2.15=h5f184b6_11
  - aws-c-http=0.6.27=hb329ca4_3
  - aws-c-io=0.13.11=h2ec9475_2
  - aws-c-mqtt=0.7.13=h5377834_9
  - aws-c-s3=0.2.1=hbdbf862_0
  - aws-c-sdkutils=0.1.7=ha56e2a8_0
  - aws-checksums=0.1.13=ha56e2a8_5
  - aws-crt-cpp=0.18.16=h14806b3_2
  - aws-sdk-cpp=1.10.55=h313beb8_0
  - babel=2.11.0=py311hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py311hca03da5_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py311h80987f9_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.15.1=py311h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311hca03da5_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cryptography=41.0.3=py311hd4332d6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dendropy=5.0.6=pyhdfd78af_0
  - entrypoints=0.4=py311hca03da5_0
  - ete3=3.1.3=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.9.0=py311hca03da5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.3.3=py311h80987f9_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gettext=0.21.0=h13f89a0_1
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h80987f9_3
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - glog=0.5.0=h5c6a83d_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - gnutls=3.6.15=h887c41c_0
  - google-auth=2.22.0=py311hca03da5_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - grpc-cpp=1.48.2=hc60591f_3
  - grpcio=1.48.2=py311hc60591f_3
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - icu=73.1=h313beb8_0
  - idna=3.4=py311hca03da5_0
  - ipykernel=6.25.0=py311hb6e6a13_0
  - ipython=8.15.0=py311hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311hca03da5_0
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.2=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311hca03da5_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter_client=7.4.9=py311hca03da5_0
  - jupyter_console=6.6.3=py311hca03da5_0
  - jupyter_core=5.3.0=py311hca03da5_0
  - jupyter_events=0.6.3=py311hca03da5_0
  - jupyter_server=1.23.4=py311hca03da5_0
  - jupyter_server_fileid=0.9.0=py311hca03da5_0
  - jupyter_server_ydoc=0.8.0=py311hca03da5_1
  - jupyter_ydoc=0.2.4=py311hca03da5_0
  - jupyterlab=3.6.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311hca03da5_0
  - jupyterlab_widgets=3.0.5=py311hca03da5_0
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=h69eda48_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang=14.0.6=default_h81a5282_0
  - libclang13=14.0.6=default_he70ec0d_0
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libllvm14=14.0.6=h19fdd8a_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.20=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=h7a5bd25_2
  - libtasn1=4.19.0=h80987f9_0
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.10.4=h0dcf63f_1
  - libxslt=1.1.37=h80987f9_1
  - lightning=2.2.4=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lxml=4.9.3=py311h50ffb84_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py311hca03da5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h80987f9_0
  - matplotlib=3.8.0=py311hca03da5_0
  - matplotlib-base=3.8.0=py311h7aedaa7_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=0.8.4=py311h80987f9_1000
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - multidict=6.0.2=py311h80987f9_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclassic=0.5.5=py311hca03da5_0
  - nbclient=0.5.13=py311hca03da5_0
  - nbconvert=6.5.4=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py311hca03da5_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.1=py311hca03da5_0
  - notebook=6.5.4=py311hca03da5_1
  - notebook-shim=0.2.2=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.0=py311he598dae_0
  - numpy-base=1.26.0=py311hfbfe69c_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.5.0=h81ee809_0
  - orc=1.7.4=hdca1487_1
  - packaging=23.1=py311hca03da5_0
  - pandas=2.2.1=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py311h3b245a6_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=3.10.0=py311hca03da5_0
  - ply=3.11=pyhd8ed1ab_2
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.36=py311hca03da5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.0=py311h80987f9_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=14.0.2=py311ha07b5f9_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pyjwt=2.4.0=py311hca03da5_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pyqt=5.15.10=py311h313beb8_0
  - pyqt5-sip=12.13.0=py311h80987f9_0
  - pyrsistent=0.18.0=py311h80987f9_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - pytorch=2.1.1=py3.11_0
  - pytorch-lightning=2.2.2=pyhd8ed1ab_0
  - pytz=2023.3.post1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=23.2.0=py311h313beb8_0
  - qt-main=5.15.2=h0917680_10
  - qtconsole-base=5.4.4=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311hca03da5_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sip=6.7.12=py311h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.2.0=py311hca03da5_1
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py311h80987f9_0
  - sympy=1.11.1=py311hca03da5_0
  - tensorboard=2.12.1=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - terminado=0.17.1=py311hca03da5_0
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py311hca03da5_0
  - torchaudio=2.1.1=py311_cpu
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - torchvision=0.16.1=py311_cpu
  - tornado=6.3.3=py311h80987f9_0
  - traitlets=5.7.1=py311hca03da5_0
  - typer=0.12.3=pyhd8ed1ab_0
  - typer-slim=0.12.3=pyhd8ed1ab_0
  - typer-slim-standard=0.12.3=hd8ed1ab_0
  - typing-extensions=4.7.1=py311hca03da5_0
  - typing_extensions=4.7.1=py311hca03da5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=0.58.0=py311hca03da5_4
  - werkzeug=2.2.3=py311hca03da5_0
  - wheel=0.41.2=py311hca03da5_0
  - widgetsnbextension=4.0.5=py311hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xorg-libice=1.1.1=hd74edd7_1
  - xorg-libsm=1.2.4=hd74edd7_1
  - xorg-libx11=1.8.10=h2321a68_0
  - xorg-libxau=1.0.11=hd74edd7_1
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxrender=0.9.11=hd74edd7_1
  - xorg-xextproto=7.3.0=hd74edd7_1004
  - xorg-xorgproto=2024.1=hd74edd7_1
  - xz=5.4.2=h80987f9_0
  - y-py=0.5.9=py311ha6e5c4f_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.8.1=py311h80987f9_0
  - ypy-websocket=0.8.2=py311hca03da5_0
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - audioread==3.0.1
      - biopython==1.83
      - ccmgen==1.0.0
      - colorlover==0.3.0
      - joblib==1.3.2
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.1
      - logomaker==0.8
      - msgpack==1.0.7
      - msgpack-python==0.5.6
      - niemads==1.0.16
      - numba==0.58.1
      - plotly==5.23.0
      - pooch==1.8.0
      - pyparsing==3.1.1
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - soundfile==0.12.1
      - soxr==0.3.7
      - tenacity==9.0.0
      - threadpoolctl==3.2.0
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-summary==1.4.5
      - torchplot==0.2.0
      - tqdm==4.66.1
      - treecluster==1.0.4
      - treeswift==1.1.44
